### ISSUE TITLE
Turn off n/no-extraneous-import

### ISSUE THREAD

**Issue by OmarJaroudi** [open-turo/eslint-config-typescript#357]
@tagoro9 @michaeljaltamirano 
It seems that file extensions like .json and .svg now count as extraneous after the eslint-plugin-n upgrade in https://github.com/open-turo/eslint-config-typescript/pull/356. So eslint is erroring out when we import those files explicitly. We already turn off this rule in some repos, thoughts about turning it off at the source if we already use things like `eslint-plugin-import`?

**Comment by michaeljaltamirano** [comment]
@OmarJaroudi I wonder if setting some options (https://github.com/mysticatea/eslint-plugin-node/blob/master/docs/rules/no-extraneous-import.md#options) could resolve it, but I am not opposed to disabling it. 👍
